### ISSUE TITLE
Не стоит использовать jQuery на сервере. 

### ISSUE THREAD

**Issue by borius** [WikiSocium/WikiSocium#16]
Только для jQ.parseJSON()? 

Тогда вы не правы, ведь ....

в js (в большинстве современных браузеров, и точно уж в nodejs) есть объект JSON у которого есть два метода: 
JSON.parse(string); 
JSON.stringify(obj);

**Comment by kukushechkin** [comment]
Да, в этом есть резон. Спасибо.
