### ISSUE TITLE
Сравнить библиотеки рисования графов

### ISSUE THREAD

**Issue by kukushechkin** [WikiSocium/WikiSocium#2]
« По поводу графов: наткнулся на любопытные библиотеки для их рисования
http://code.google.com/apis/chart/image/docs/gallery/graphviz.html
http://arborjs.org/ 
http://code.google.com/apis/chart/interactive/docs/gallery/orgchart.html »

Инициатива наказуема :)

В коде уже есть какая-то библиотека, и она даже рисует графы, но мне очень не нравится большое количество зависимостей в ней, да и вообще она какая-то кривая (одним словом первая ссылка в гугле). Нужно выяснить, можно ли минимальной кровью рисовать графы с необходимым нам алгоритмом расположения вершин и их стилями (например, задающимися css-стилями).

**Comment by nzav** [comment]
Постараюсь успеть посмотреть к встрече :) Но предоставляю эту возможность всем желающим)

**Comment by dukanevskiy** [comment]
Ребята, я бы сейчас рассматривал подобные задачи с наименьшим приоритетом. Конечно, рисование графов - полезная штука. Но нам бы пока сделать хотя бы какой-нибудь навигатор по решению, пусть он будет вообще без возможности перехода к любому шагу, пусть в описании решения просто выдаётся список шагов - но он будет. А так вы сейчас уйдёте искать крутейшую библиотеку рисования графов (задача кстати очень нетривиальная) и вернётесь через полгода
