### ISSUE TITLE
Генератор форм

### ISSUE THREAD

**Issue by nzav** [WikiSocium/WikiSocium#3]
Итак.. Вот список того, что потениально может пригодиться:
1). Orbeon
- для его развертывания необходимо ставить tomcat, что невозможно с нашим нодом, насколько я понимаю (хотя, как утверждают некоторые маны, можно заставить работать нод параллельно с другими серверами (proof: http://arguments.callee.info/2010/04/20/running-apache-and-node-js-together/ ))
- красиво и вроде удобно
  2). WebFormFactory
- написан на PHP
  3). jFormer (http://www.jformer.com)
- Опять же для развертывания нужна поддержка РНР, но из JS куска можно выдернуть что-то полезное наверняка
- красиво и анимированно
  4). InputEx (http://neyric.github.com/inputex/)
- Реализован полностью на JS, не надо ничего мудрить
- Генерация форм из JSON'а
  5). LiveValidation (не генератор, но готовое решение для валидации) (http://livevalidation.com/)

Итого, стоит копать, в первую очередь, inputex, если найдется кардинальный непоправимый косяк, то пробовать другое.
UPDATE:
Залил на пробный хостинг inputex: http://testmaps.gixx.ru/inputex/
Внизу много ссылочек на примеры с исходниками. Много плюшек и все удобно. Мне понравилось.

**Comment by dukanevskiy** [comment]
Опять же, я не разработчик, но jFormer и InputEx вдохновляют - кажется, их действительно можно раздербанивать для своих целей, как говорил Серёга...

-----Original Message-----
From: zaff [mailto:reply@reply.github.com] 
Sent: Thursday, October 27, 2011 11:19 PM
To: dukanevskiy
Subject: [WikiSocium] Генератор форм (#3)

Итак.. Вот список того, что потениально может пригодиться:
1). Orbeon
2). WebFormFactory
3). jFormer (http://www.jformer.com)
4). InputEx (http://neyric.github.com/inputex/)
5). LiveValidation (не генератор, но готовое решение для валидации) (http://livevalidation.com/)

Сегодня-завтра распишу про то, что посмотрел из этого списка. Времени на этой неделе не очень много.

## 

Reply to this email directly or view it on GitHub:
https://github.com/WikiSocium/WikiSocium/issues/3
